name: .NET Core

on:
  push:
    branches: [ main ]
#    paths:
#      - 'apis/poi*'
  pull_request:
    branches: [ main ]
    paths:
      - 'apis/poi*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
       
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./apis/poi
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./apis/poi
    - name: Test
      env:
        SQL_DBNAME: ${{ secrets.SQL_DBNAME }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_SERVER: ${{ secrets.SQL_SERVER }}
        SQL_USER: ${{ secrets.SQL_USER }}
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./apis/poi
